export const questions = [
  {
    id: 1,
    question: "What color is the sky?",
    a: "Blue",
    b: "Red",
    c: "Green",
    d: "Yellow",
    correctAns: "a",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 2,
    question: "How many legs does a cat have?",
    a: "2",
    b: "4",
    c: "6",
    d: "8",
    correctAns: "b",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 3,
    question: "What is 1 + 1?",
    a: "1",
    b: "3",
    c: "2",
    d: "4",
    correctAns: "c",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 4,
    question: "What do you drink when you are thirsty?",
    a: "Milk",
    b: "Juice",
    c: "Water",
    d: "Oil",
    correctAns: "c",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 5,
    question: "What sound does a dog make?",
    a: "Meow",
    b: "Woof",
    c: "Moo",
    d: "Tweet",
    correctAns: "b",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 6,
    question: "What do you wear on your feet?",
    a: "Shirt",
    b: "Pants",
    c: "Hat",
    d: "Shoes",
    correctAns: "d",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 7,
    question: "What do bees make?",
    a: "Milk",
    b: "Water",
    c: "Honey",
    d: "Juice",
    correctAns: "c",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 8,
    question: "Which one is a fruit?",
    a: "Carrot",
    b: "Apple",
    c: "Potato",
    d: "Broccoli",
    correctAns: "b",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 9,
    question: "Which animal says 'meow'?",
    a: "Dog",
    b: "Cat",
    c: "Cow",
    d: "Duck",
    correctAns: "b",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 10,
    question: "What do you see with?",
    a: "Ears",
    b: "Nose",
    c: "Eyes",
    d: "Mouth",
    correctAns: "c",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 11,
    question: "How many days are in a week?",
    a: "5",
    b: "6",
    c: "7",
    d: "8",
    correctAns: "c",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 12,
    question: "Which one is cold?",
    a: "Ice",
    b: "Fire",
    c: "Sun",
    d: "Oven",
    correctAns: "a",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 13,
    question: "What do you use to write?",
    a: "Spoon",
    b: "Pen",
    c: "Fork",
    d: "Knife",
    correctAns: "b",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 14,
    question: "Where do fish live?",
    a: "Sky",
    b: "Ground",
    c: "Water",
    d: "Tree",
    correctAns: "c",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 15,
    question: "What color is a banana?",
    a: "Red",
    b: "Yellow",
    c: "Green",
    d: "Blue",
    correctAns: "b",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
];




export const prizeMap = {
  0:0,
  1: 200,
  2: 300,
  3: 500,
  4: 1000,
  5: 2000,
  6: 5000,
  7: 10000,
  8: 15000,
  9: 25000,
  10: 50000,
  11: 75000,
  12: 100000,
  13: 150000,
  14: 250000,
  15: 500000,
};
