export const questions = [
  {
    id: 1,
    question: "How are you today????",
    a: "hmm",
    b: "Uhm",
    c: "Good",
    d: "Cook",
    correctAns: "d",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 2,
    question: "What is the capital of France?",
    a: "London",
    b: "Paris",
    c: "Berlin",
    d: "Madrid",
    correctAns: "d",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 3,
    question: "Which planet is known as the Red Planet?",
    a: "Earth",
    b: "Mars",
    c: "Venus",
    d: "Jupiter",
    correctAns: "d",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 4,
    question: "What is 2 + 2?",
    a: "3",
    b: "4",
    c: "5",
    d: "22",
    correctAns: "d",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 5,
    question: "What color do you get when you mix red and blue?",
    a: "Purple",
    b: "Orange",
    c: "Green",
    d: "Pink",
    correctAns: "d",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 6,
    question: "What is the largest mammal?",
    a: "Elephant",
    b: "Blue Whale",
    c: "Giraffe",
    d: "Rhino",
    correctAns: "d",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 7,
    question: "Which continent is Egypt located in?",
    a: "Africa",
    b: "Asia",
    c: "Europe",
    d: "Australia",
    correctAns: "d",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 8,
    question: "What is the boiling point of water?",
    a: "90°C",
    b: "100°C",
    c: "120°C",
    d: "80°C",
    correctAns: "d",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 9,
    question: "Which animal is known as the king of the jungle?",
    a: "Tiger",
    b: "Elephant",
    c: "Lion",
    d: "Bear",
    correctAns: "d",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 10,
    question: "What gas do plants use for photosynthesis?",
    a: "Oxygen",
    b: "Hydrogen",
    c: "Carbon Dioxide",
    d: "Nitrogen",
    correctAns: "d",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 11,
    question: "What shape has three sides?",
    a: "Circle",
    b: "Triangle",
    c: "Square",
    d: "Rectangle",
    correctAns: "d",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 12,
    question: "Which season comes after summer?",
    a: "Winter",
    b: "Autumn",
    c: "Spring",
    d: "Rainy",
    correctAns: "d",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 13,
    question: "What color is the sky on a clear day?",
    a: "Blue",
    b: "Red",
    c: "Green",
    d: "Yellow",
    correctAns: "d",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 14,
    question: "Which sense do we use to smell?",
    a: "Sight",
    b: "Touch",
    c: "Hearing",
    d: "Smell",
    correctAns: "d",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 15,
    question: "How many legs does a spider have?",
    a: "6",
    b: "8",
    c: "10",
    d: "12",
    correctAns: "d",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
];



export const prizeMap = {
  0:0,
  1: 200,
  2: 300,
  3: 500,
  4: 1000,
  5: 2000,
  6: 5000,
  7: 10000,
  8: 15000,
  9: 25000,
  10: 50000,
  11: 75000,
  12: 100000,
  13: 150000,
  14: 250000,
  15: 500000,
};
