export const questions = [
  {
    id: 1,
    question: "Bầu trời có màu gì?",
    a: "Xanh",
    b: "Đỏ",
    c: "Xanh lá",
    d: "Vàng",
    correctAns: "a",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 2,
    question: "Một con mèo có bao nhiêu chân?",
    a: "2",
    b: "4",
    c: "6",
    d: "8",
    correctAns: "b",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 3,
    question: "1 + 1 bằng bao nhiêu?",
    a: "1",
    b: "3",
    c: "2",
    d: "4",
    correctAns: "c",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 4,
    question: "Bạn uống gì khi khát?",
    a: "Sữa chua",
    b: "Nước biển",
    c: "Nước khoáng đóng chai",
    d: "Dầu",
    correctAns: "c",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 5,
    question: "Chó kêu như thế nào?",
    a: "Meo meo",
    b: "Gâu gâu",
    c: "Ò ò",
    d: "Chíp chíp",
    correctAns: "b",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 6,
    question: "Bạn mang gì ở chân?",
    a: "Áo",
    b: "Quần",
    c: "Mũ",
    d: "Giày",
    correctAns: "d",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 7,
    question: "Ong làm ra gì?",
    a: "Sữa",
    b: "Nước",
    c: "Mật ong",
    d: "Nước ép",
    correctAns: "c",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 8,
    question: "Loại nào là trái cây?",
    a: "Cà rốt",
    b: "Táo",
    c: "Khoai tây",
    d: "Bông cải xanh",
    correctAns: "b",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 9,
    question: "Con vật nào kêu 'meo meo'?",
    a: "Chó",
    b: "Mèo",
    c: "Bò",
    d: "Vịt",
    correctAns: "b",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 10,
    question: "Bạn nhìn bằng gì?",
    a: "Tai",
    b: "Mũi",
    c: "Mắt",
    d: "Miệng",
    correctAns: "c",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 11,
    question: "Một tuần có bao nhiêu ngày?",
    a: "5",
    b: "6",
    c: "7",
    d: "8",
    correctAns: "c",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 12,
    question: "Cái nào lạnh?",
    a: "Đá",
    b: "Lửa",
    c: "Mặt trời",
    d: "Lò nướng",
    correctAns: "a",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 13,
    question: "Bạn dùng gì để viết?",
    a: "Muỗng",
    b: "Bút",
    c: "Nĩa",
    d: "Dao",
    correctAns: "b",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 14,
    question: "Cá sống ở đâu?",
    a: "Bầu trời",
    b: "Mặt đất",
    c: "Nước",
    d: "Cây",
    correctAns: "c",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
  {
    id: 15,
    question: "Chuối có màu gì?",
    a: "Đỏ",
    b: "Vàng",
    c: "Xanh lá",
    d: "Xanh dương",
    correctAns: "b",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
  },
];


export const allOptions = ["a", "b", "c", "d"];

export const prizeMap = {
  0: 0,
  1: 200000,
  2: 500000,
  3: 1000000,
  4: 2000000,
  5: 3000000,
  6: 5000000,
  7: 7000000,
  8: 10000000,
  9: 14000000,
  10: 20000000,
  11: 30000000,
  12: 40000000,
  13: 60000000,
  14: 85000000,
  15: 150000000,
};
